all:	prompt command1 command2 command2b command3 command3b

prompt:	prompt.c
	gcc -Wall -o prompt prompt.c

command1:	command1.c
	gcc -Wall -o command1 command1.c

command2:	command2.c
	gcc -Wall -o command2 command2.c

command3:	command3.c
	gcc -Wall -o command3 command3.c

command2b:	command2b.c
	gcc -Wall -o command2b command2b.c

command3b:	command3b.c
	gcc -Wall -o command3b command3b.c

clean:	
	rm prompt command1 command2 command3 command2b command3b 

